
PASS # AUDIT TASK RUNNER STARTED. 
PASS Executing "initialize" 
PASS Executing "invalid constructor" 
FAIL Executing "default constructor" promise_test: Unhandled rejection with value: object "TypeError: undefined is not an object (evaluating 'node.numberOfInputs')"
FAIL Executing "test AudioNodeOptions" promise_test: Unhandled rejection with value: object "TypeError: undefined is not an object (evaluating 'node.channelCount')"
FAIL Executing "constructor options" promise_test: Unhandled rejection with value: object "TypeError: undefined is not an object (evaluating 'node.delayTime')"
PASS Audit report 
PASS > [initialize]  
PASS   context = new OfflineAudioContext(...) did not throw an exception. 
PASS < [initialize] All assertions passed. (total 1 assertions) 
PASS > [invalid constructor]  
PASS   new DelayNode() threw TypeError: "function is not a constructor (evaluating 'new window[name]()')". 
PASS   new DelayNode(1) threw TypeError: "function is not a constructor (evaluating 'new window[name](1)')". 
PASS   new DelayNode(context, 42) threw TypeError: "function is not a constructor (evaluating 'new window[name](context, 42)')". 
PASS < [invalid constructor] All assertions passed. (total 3 assertions) 
PASS > [default constructor]  
FAIL X node0 = new DelayNode(context) incorrectly threw TypeError: "function is not a constructor (evaluating 'new window[name](context, options.constructorOptions)')". assert_true: expected true got false
FAIL X node0 instanceof DelayNode is not equal to true. Got false. assert_true: expected true got false
PASS > [test AudioNodeOptions]  
FAIL X new DelayNode(c, {channelCount: 17}) incorrectly threw TypeError: "function is not a constructor (evaluating 'new window[nodeName]')". assert_true: expected true got false
PASS > [constructor options]  
FAIL X node1 = new DelayNode(c, {"delayTime":0.5,"maxDelayTime":1.5}) incorrectly threw TypeError: "function is not a constructor (evaluating 'new DelayNode(context, options)')". assert_true: expected true got false
FAIL # AUDIT TASK RUNNER FINISHED: 3 out of 5 tasks were failed. assert_true: expected true got false

