<html>
<head>
<meta charset='utf-8'>
<style>
.pass {
    font-weight: bold;
    color: green;
}
.fail {
    font-weight: bold;
    color: red;
}
</style>

<script>
if (window.testRunner)
    testRunner.dumpAsText();

function SputnikError(message)
{
    this.message = message;
}

SputnikError.prototype.toString = function ()
{
    return 'SputnikError: ' + this.message;
};

var sputnikException;

function testPrint(msg)
{
    var span = document.createElement("span");
    document.getElementById("console").appendChild(span); // insert it first so XHTML knows the namespace 
    span.innerHTML = msg + '<br />';
}

function escapeHTML(text)
{
    return text.toString().replace(/&/g, "&amp;").replace(/</g, "&lt;");
}

function printTestPassed(msg)
{
    testPrint('<span><span class="pass">PASS</span> ' + escapeHTML(msg) + '</span>');
}

function printTestFailed(msg)
{
    testPrint('<span><span class="fail">FAIL</span> ' + escapeHTML(msg) + '</span>');
}

function testFailed(msg)
{
    throw new SputnikError(msg);
}

var successfullyParsed = false;
</script>

</head>
<body>
<p>S12.14_A7_T1</p>
<div id='console'></div>
<script>
try {

/**
 * @name: S12.14_A7_T1;
 * @section: 12.14;
 * @assertion: Evaluating the nested productions TryStatement;
 * @description: Checking if the production of nested TryStatement statements evaluates correct;
 */

// CHECK#1
try{
  try{
    throw "ex2";
  }
  catch(er2){
    if (er2!=="ex2")
      testFailed('#1.1: Exception === "ex2". Actual:  Exception ==='+ e  );
      throw "ex1";
    }
  }
  catch(er1){
    if (er1!=="ex1") testFailed('#1.2: Exception === "ex1". Actual: '+er1);
    if (er1==="ex2") testFailed('#1.3: Exception !== "ex2". Actual: catch previous embedded exception');
}

// CHECK#2
try{
  throw "ex1";
}
catch(er1){
  try{
    throw "ex2";
  }
  catch(er1){
    if (er1==="ex1") testFailed('#2.1: Exception !== "ex1". Actual: catch previous catching exception');
    if (er1!=="ex2") testFailed('#2.2: Exception === "ex2". Actual:  Exception ==='+ er1  );
  }
  if (er1!=="ex1") testFailed('#2.3: Exception === "ex1". Actual:  Exception ==='+ er1  );
  if (er1==="ex2") testFailed('#2.4: Exception !== "ex2". Actual: catch previous catching exception');
}

// CHECK#3
try{
  throw "ex1";
}
catch(er1){
  if (er1!=="ex1") testFailed('#3.1: Exception ==="ex1". Actual:  Exception ==='+ er1  );
}
finally{
  try{
    throw "ex2";
  }
  catch(er1){
    if (er1==="ex1") testFailed('#3.2: Exception !=="ex1". Actual: catch previous embedded exception');
    if (er1!=="ex2") testFailed('#3.3: Exception ==="ex2". Actual:  Exception ==='+ er1  );
  }
}

// CHECK#4
var c4=0;
try{
  throw "ex1";
}
catch(er1){
  try{
    throw "ex2";
  }
  catch(er1){
    if (er1==="ex1") testFailed('#4.1: Exception !=="ex1". Actual: catch previous catching exception');
    if (er1!=="ex2") testFailed('#4.2: Exception ==="ex2". Actual:  Exception ==='+ er1  );
  }
  if (er1!=="ex1") testFailed('#4.3: Exception ==="ex1". Actual:  Exception ==='+ er1  );
  if (er1==="ex2") testFailed('#4.4: Exception !=="ex2". Actual: Catch previous embedded exception');
}
finally{
  c4=1;
}
if (c4!==1) testFailed('#4.5: "finally" block must be evaluated');

// CHECK#5
var c5=0;
try{
  try{
    throw "ex2";
  }
  catch(er1){
    if (er1!=="ex2") testFailed('#5.1: Exception ==="ex2". Actual:  Exception ==='+ er1  );
  }
  throw "ex1";
}
catch(er1){
  if (er1!=="ex1") testFailed('#5.2: Exception ==="ex1". Actual:  Exception ==='+ er1  );
  if (er1==="ex2") testFailed('#5.3: Exception !=="ex2". Actual: catch previous embedded exception');
}
finally{
  c5=1;
}
if (c5!==1) testFailed('#5.4: "finally" block must be evaluated');

// CHECK#6
var c6=0;
try{
  try{
    throw "ex1";
  }
  catch(er1){
    if (er1!=="ex1") testFailed('#6.1: Exception ==="ex1". Actual:  Exception ==='+ er1  );
  }
}
finally{
  c6=1;		
}
if (c6!==1) testFailed('#6.2: "finally" block must be evaluated');

// CHECK#7
var c7=0;
try{
  try{
    throw "ex1";
  }
  finally{
    try{
      c7=1;
      throw "ex2";
    }
    catch(er1){
      if (er1!=="ex2") testFailed('#7.1: Exception ==="ex2". Actual:  Exception ==='+ er1  );
      if (er1==="ex1") testFailed('#7.2: Exception !=="ex1". Actual: catch previous embedded exception');
      c7++;
    }
  }
}
catch(er1){
  if (er1!=="ex1") testFailed('#7.3: Exception ==="ex1". Actual:  Exception ==='+ er1  );
}
if (c7!==2) testFailed('#7.4: "finally" block must be evaluated');

} catch (ex) {
    sputnikException = ex;
}

var successfullyParsed = true;
</script>

<script>
if (!successfullyParsed)
    printTestFailed('successfullyParsed is not set');
else if (sputnikException)
    printTestFailed(sputnikException);
else
    printTestPassed("");
testPrint('<br /><span class="pass">TEST COMPLETE</span>');
</script>
</body>
</html>
